name: job_jungle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_core: ^2.27.0
  google_fonts: 6.1.0
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets/