// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh--NnyCnPbkGo7FnDDSzUUkxFsqAHkVw',
    appId: '1:49137141662:web:5373e4139ab7c23749f88f',
    messagingSenderId: '49137141662',
    projectId: 'job-jungle-rev2-7dfd0',
    authDomain: 'job-jungle-rev2-7dfd0.firebaseapp.com',
    storageBucket: 'job-jungle-rev2-7dfd0.appspot.com',
    measurementId: 'G-SZNYZ736HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW4RZ3584mLiw4FRGHY0TQppOccYd5UNE',
    appId: '1:49137141662:android:f5dada3a406f7d8549f88f',
    messagingSenderId: '49137141662',
    projectId: 'job-jungle-rev2-7dfd0',
    storageBucket: 'job-jungle-rev2-7dfd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3tf9cCN7quJTBe5c58mhdp3d7tCH8rs8',
    appId: '1:49137141662:ios:f6ae9f27984c57dc49f88f',
    messagingSenderId: '49137141662',
    projectId: 'job-jungle-rev2-7dfd0',
    storageBucket: 'job-jungle-rev2-7dfd0.appspot.com',
    iosBundleId: 'com.example.jobJungle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3tf9cCN7quJTBe5c58mhdp3d7tCH8rs8',
    appId: '1:49137141662:ios:f6ae9f27984c57dc49f88f',
    messagingSenderId: '49137141662',
    projectId: 'job-jungle-rev2-7dfd0',
    storageBucket: 'job-jungle-rev2-7dfd0.appspot.com',
    iosBundleId: 'com.example.jobJungle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh--NnyCnPbkGo7FnDDSzUUkxFsqAHkVw',
    appId: '1:49137141662:web:69949e3cab0f91be49f88f',
    messagingSenderId: '49137141662',
    projectId: 'job-jungle-rev2-7dfd0',
    authDomain: 'job-jungle-rev2-7dfd0.firebaseapp.com',
    storageBucket: 'job-jungle-rev2-7dfd0.appspot.com',
    measurementId: 'G-13Z65SDNN5',
  );
}
